recipeDetailsOpen = 'recipe-details-open'
recipeDetailsClose = 'recipe-details-close'
notificationOpen = 'notification-open'
notificationClose = 'notification-close'
consoleOpen = 'console-open'
consoleClose = 'console-close'
scheduleOpen = 'schedule-open'
scheduleClose = 'schedule-close'

api_key = 'http://192.168.178.33:45455/api'